
GEMINI_API_KEY ="AIzaSyAvkbylW62gboSM7oq43Mfw9VseFowvw1c"
TWILIO_ACCOUNT_SID = "AC587a2d40d3a1a41c4702bda5758b42d6"
TWILIO_AUTH_TOKEN = "601a1ffcfceda80b8e8ac7e59409ae50"
MY_PHONE_NUMBER="+916362516968"
TWILIO_WHATSAPP_FROM ="+18145267079"
# Angel One SmartAPI Credentials
ANGEL_ONE_API_KEY = "GvCGuULI"
ANGEL_ONE_TOTP_SECRET = "HBZNZU7YCG35O4JHTE622JC64Q"
ANGEL_ONE_CLIENT_CODE = "A507943"
ANGEL_ONE_PIN = "1181"

# Weather API Key
OPENWEATHER_API_KEY = "54cbb3024ac31e9f8849560e545aff11"
